README.md, cmd/interfaces.go, cmd/listen.go, cmd/send.go
merge to getting-started since this seems to be the way to go.
=> Pcap inject

.github/workflows/go.yaml, Makefile
=> add 'test-fmt' target

cmd/interfaces.go, cmd/listen.go, cmd/main.go, cmd/send.go, go.mod, go.sum
that's a first draft ; thanks for the opportunity and feedback appreciated. I made also some small refactoring and typo fixing, also in order to made linter happier ...
The compilation went fine; but is there a procedure to follow in order to test the working of the udp proxy ?
=> unified listen and promisc interfaces using autodetection

CHANGELOG.md, cmd/listen.go
=> Add LinkTypeRaw support for Wireguard

CHANGELOG.md, Makefile, str2pcap/main.go
Super basic right now.  Need to add unit tests & actually parse the log?
=> Add str2pcap tool for taking debug logs and making a pcap

.gitignore, CHANGELOG.md, Dockerfile.arm64, Makefile
- Not actually working- strange compile bug where getting undefined
function calls to functions defined in interfaces.go
Fixes: #31
=> ARM64/Linux cross-compile support

Dockerfile, Makefile
Don't need that old Dockerfile anymore. Cleanup targets and fix
clean-docker
=> More Makefile/docker cleanup

CHANGELOG.md, Dockerfile, Makefile, README.md, startup-scripts/Docker/README.md, startup-scripts/Docker/docker-compose.yaml, startup-scripts/README.md, startup-scripts/pfSense/README.md, startup-scripts/pfSense/etc/rc.conf.local, startup-scripts/pfSense/usr/local/etc/rc.d/udp-proxy-2020, startup-scripts/pfSense/usr/local/etc/udp-proxy-2020.conf
- Build a docker container
- Use Docker for UDM/UDMPro and docker-compose
- Add pfSense scripts
=> Add startup scripts for pfSense & UDM/UDMPro & Docker

Dockerfile.arm32, Dockerfile.arm32hf, Dockerfile.arm64, Makefile, README.md
=> Add support for ARM32EL & ARM32HF

cmd/main.go
=> Add --logfile to send logs to a file instead stderr

CHANGELOG.md, Dockerfile, Makefile, Vagrantfile, cmd/main.go, startup-scripts/pfSense/usr/local/etc/udp-proxy-2020.conf
- No actual code changes, but lots of docs and platfor improvements
- Update docker container
- Add ARM64 container for UDM, etc
=> release v0.0.7

.gitignore, CHANGELOG.md, Makefile, Vagrantfile
Matches the OS used for pfSense 2.5.x
=> Use FreeBSD 12.2 for building binary

CHANGELOG.md, Makefile, Vagrantfile
Add support for building FreeBSD binaries targeting:
- ARM64 (aarch64)
- ARMv6
- ARMv7
Fixes: #53
=> Add cross compile FreeBSD support

CHANGELOG.md, Makefile, cmd/interfaces.go, cmd/listen.go, cmd/utils.go, go.mod, go.sum, startup-scripts/pfSense/usr/local/etc/udp-proxy-2020.conf
- use: src net x.x.x.x/y  in BPF filter #71
- Improved debug output with spew
- tweak sample config file for freebsd/pfSense
- release v0.0.8
=> BPF filter uses src net

README.md, cmd/main.go
* revert timeout change in last PR
* update cache-ttl to be in minutes (change default to 3hrs)
* Update readme for this and ARM build changes
=> revert timeout and add --cache-ttl

CHANGELOG.md, Dockerfile, Makefile
=> small bugfixes for makefile & dockerfile

CHANGELOG.md, Dockerfile, Makefile, README.md
=> Fix docker image

.github/workflows/golangci-lint.yaml, .github/workflows/md-links-check.yml, go.mod, go.sum, startup-scripts/udm-utilities/README.md
update net library to v0.7.0 for security
=> add md-links-check to workflows & security

startup-scripts/Docker/README.md, startup-scripts/Docker/docker-compose.yaml
=> Update docker-compose config

.github/workflows/build-release.yml, .github/workflows/build.yml, CHANGELOG.md, Dockerfile, Dockerfile.package, Makefile, README.md, package.sh
- clean up readme
- update changelog
- build RPM/DEB packages
- fix Dockerfile.package to build
=> clean up to get ready for v0.1.0
